spring:
  application:
    name: springcloud-demo-eureka-client
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # status 的名称
    #instance-id: test
    prefer-ip-address: true
